# Define the version of Docker Compose file format
version: '3.8'

services:
  # Define a service named 'app'
  app:
    # Build the Docker image from the Dockerfile in the current directory
    build: .
    
    # Map port 8080 on the host to port 8080 in the container
    ports:
      - "8080:8080"
    
    # Automatically restart the container if it stops or if Docker daemon is restarted
    restart: always
